### PR TITLE
Handle the milestone bugs

### LINKED ISSUE #10: Automate adding and removing "For Milestone Bug"
https://github.com/microsoft/TypeScript/labels/For%20Milestone%20Bug

### PR DESCRIPTION
**Pull request by orta**
Fixes #10

### CODE REVIEW

File: src/checks/addMilestoneLabelsToPRs.ts [hunk 1]
```diff
@@ -0,0 +1,56 @@
+import { WebhookPayloadPullRequest } from "@octokit/webhooks"
+import { Octokit } from "@octokit/rest"
+import { Logger } from "@azure/functions"
+import { getRelatedIssues } from "../pr_meta/getRelatedIssues"
+
+/**
+ * Keep track of the milstone
+ */
+export const addMilestoneLabelsToPRs = async (api: Octokit, payload: WebhookPayloadPullRequest, logger: Logger) => {
```
Comment (sandersn) [inline src/checks/addMilestoneLabelsToPRs.ts:9]: this gets run on each PR periodically, I take it?

Comment (orta) [reply src/checks/addMilestoneLabelsToPRs.ts:9]: Any of these trigger it:

Screen Shot 2020-07-15 at 12 12 30 PM

I will probably make a daily PR run
